#!/bin/bash

BRIGHTNESSPERC=$(($(($(brightnessctl g)*100))/255))

if [[ $BRIGHTNESSPERC -le 30 ]]; then
    BRIGHTNESSFORMATTED="󰃞 $BRIGHTNESSPERC%"
elif [[ $BRIGHTNESSPERC -le 60 ]]; then
    BRIGHTNESSFORMATTED="󰃟 $BRIGHTNESSPERC%"
else
    BRIGHTNESSFORMATTED="󰃠 $BRIGHTNESSPERC%"
fi

echo $BRIGHTNESSFORMATTED
